"""user avatar

Revision ID: 203f2b529c09
Revises: ae0eb0c2f09e
Create Date: 2026-08-04 01:00:58.326354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203f2b529c09'
down_revision = 'ae0eb0c2f09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
