"""coupon image_url

Revision ID: 3d88a1a1a423
Revises: 203f2b529c09
Create Date: 2026-08-09 18:55:06.250249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d88a1a1a423'
down_revision = '203f2b529c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
