"""subscriber location and ip fields

Revision ID: a0425f18165e
Revises: e1f8c3a4b206
Create Date: 2026-08-24 23:22:44.390697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0425f18165e'
down_revision = 'e1f8c3a4b206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic | please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.create_foreign_key('fk_subscriber_store_id', 'stores', ['store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic | please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscriber_store_id', type_='foreignkey')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###
