"""Generate builder-bp.css — tablet/desktop overrides for per-screen redesign."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARTS = ROOT / "app" / "static" / "css" / "builder-parts.css"
BASE = ROOT / "app" / "static" / "css" / "builder.css"
OUT = ROOT / "app" / "static" / "css" / "builder-bp.css"

ROLES = (
    "title", "titlehl", "sub", "body", "eyebrow", "cardtitle",
    "cardtext", "btn", "nav", "meta",
)
PROPS = (
    "family", "color", "weight", "lh", "track", "case", "italic",
    "align", "maxw", "mt", "mb", "shadow",
)
SECTION_VARS = (
    "bg", "hcolor", "tcolor", "font", "overlay", "cardbg", "cardborder",
    "cardhead", "cardtext", "cardradius", "bodyfont", "hweight", "case",
    "lh", "accent", "overlaycolor", "btnbg", "btntext", "shadow",
    "imgoverlay", "bweight", "italic", "divider", "bgsize", "bgpos",
    "bgrepeat", "gradfrom", "gradto", "graddir", "imgfilter", "link",
    "valign", "btnborder", "navlink", "iconcolor", "squigcolor", "imgfit",
    "cardcols", "xtraborder", "xtrashadow", "xtraalign", "btnradius",
    "tracking", "hsize", "maxw", "imgradius", "bsize", "hlh", "cardpad",
    "cardborderw", "cardw", "cardh", "textw", "minh", "px", "logoh",
    "squigw", "imgh", "cardminw", "gap", "xtraw", "xtrah", "xtraradius",
    "xtraborderw",
)


def collect_rules(src: str, var_name: str) -> list[tuple[str, str]]:
    """Find rules whose attribute selector mentions --pb-{var_name}:."""
    needle = f'--pb-{var_name}:'
    out = []
    # walk each occurrence of the attribute selector and expand to the rule body
    for m in re.finditer(re.escape(f'.pb-sec[style*="{needle}"]'), src):
        # find the start of this rule: rewind to previous `}` or start, then
        # forward from first .pb-sec of this rule — simpler: from m.start(),
        # find `{` that opens the body (first `{` after this match that is the rule brace)
        start = m.start()
        # include preceding selector lines that belong to the same rule
        # (they all share the same needle and sit after the previous `}`)
        prev = src.rfind("}", 0, start)
        rule_start = prev + 1
        # skip whitespace / comments at rule_start
        while rule_start < start and src[rule_start] in " \t\r\n":
            rule_start += 1
        # only accept if this block is about our var (first selector uses it)
        head = src[rule_start:start + 1]
        if needle not in src[rule_start:m.end()]:
            continue
        brace = src.find("{", m.end())
        if brace < 0:
            continue
        end = src.find("}", brace)
        if end < 0:
            continue
        selectors = src[rule_start:brace].strip()
        body = src[brace + 1:end].strip()
        if f"var(--pb-{var_name})" not in body and f"var(--pb-{var_name}," not in body:
            continue
        item = (selectors, body)
        if item not in out:
            out.append(item)
    return out


def clone_rules(rules: list[tuple[str, str]], var_name: str, bp: str) -> list[str]:
    out = []
    for selectors, body in rules:
        sel_bp = selectors.replace(f"--pb-{var_name}:", f"--pb-{var_name}{bp}:")
        body_bp = body.replace(f"var(--pb-{var_name})", f"var(--pb-{var_name}{bp})")
        out.append(f"{sel_bp}{{ {body_bp} }}")
    return out


def main() -> None:
    parts = PARTS.read_text(encoding="utf-8")
    base = BASE.read_text(encoding="utf-8")
    md_rules: list[str] = []
    lg_rules: list[str] = []

    for role in ROLES:
        for prop in PROPS:
            var = f"{role}-{prop}"
            rules = collect_rules(parts, var)
            for bp, bucket in (("md", md_rules), ("lg", lg_rules)):
                bucket.extend(clone_rules(rules, var, bp))

    for var in SECTION_VARS:
        rules = collect_rules(base, var)
        for bp, bucket in (("md", md_rules), ("lg", lg_rules)):
            bucket.extend(clone_rules(rules, var, bp))

    out = [
        "/* AUTO-GENERATED by tools/gen_builder_bp.py — do not edit by hand. */",
        "/* Tablet / desktop overrides for per-screen redesign. */",
        "",
        "@media (min-width:768px){",
        *md_rules,
        "}",
        "",
        "@media (min-width:1024px){",
        *lg_rules,
        "}",
        "",
    ]
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT} ({len(md_rules)} md + {len(lg_rules)} lg rules)")


if __name__ == "__main__":
    main()
